<?xml version="1.0" ?>
<definitions name="Login" targetNamespace="urn:Login" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:Login" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/">
<types xmlns="http://schemas.xmlsoap.org/wsdl/" />
<portType name="LoginPort"><operation name="check">
<input message="tns:checkRequest" />
<output message="tns:checkResponse" />
</operation>
</portType>
<binding name="LoginBinding" type="tns:LoginPort">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
<operation name="check">
<soap:operation soapAction="urn:Login#Login#check" />
<input><soap:body use="encoded" namespace="urn:Login" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
</input>
<output>
<soap:body use="encoded" namespace="urn:Login" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
</output>
</operation>
</binding>
<service name="Login">
<documentation />
<port name="LoginPort" binding="tns:LoginBinding"><soap:address location="http://localhost:802/server_login.php" />
</port>
</service>
<message name="checkRequest">
<part name="username" type="xsd:string" />
<part name="password" type="xsd:string" />
</message>
<message name="checkResponse">
<part name="check" type="xsd:string" />
</message>
</definitions>